version: 2.1
orbs:
  # Your orb will be automatically injected here during the pipeline.
  # Reference your orb's jobs and commands below as they will exist when built.
  orb-tools: circleci/orb-tools@12.0
  # The orb definition is intentionally not included here. It will be injected into the pipeline.
  prevent-self-approval: {}

# Use this tag to ensure test jobs always run,
# even though the downstream publish job will only run on release tags.
filters: &filters
  tags:
    only: /.*/

# Filter for release tags.
release-filters: &release-filters
  branches:
    ignore: /.*/
  tags:
    only: /^v[0-9]+\.[0-9]+\.[0-9]+$/

jobs:
  dummy-build-and-test:
    docker:
      - image: cimg/base:current
    steps:
      - run:
          name: Run build and tests
          command: echo "Running build and tests!"
  dummy-deploy:
    docker:
      - image: cimg/base:current
    steps:
      - run:
          name: Run tests
          command: echo "Running deployment!"

workflows:
  test-deploy:
    jobs:
      # Make sure to include "filters: *filters" in every test job you want to run as part of your deployment.
      # Test your orb's commands in a custom job and test your orb's jobs directly as a part of this workflow.
      - dummy-build-and-test:
          filters: *filters
      - wait-for-approval:
          type: approval
          requires:
            - dummy-build-and-test
          filters: *filters
      - prevent-self-approval/verify:
          requires:
            - wait-for-approval
          filters: *filters
      - dummy-deploy:
          requires:
            - prevent-self-approval/verify
          filters: *filters

      # The orb must be re-packed for publishing, and saved to the workspace.
      - orb-tools/pack:
          filters: *release-filters
      - orb-tools/publish:
          orb_name: tadashi0713/prevent-self-approval
          vcs_type: << pipeline.project.type >>
          pub_type: production
          # Ensure this job requires all test jobs and the pack job.
          requires:
            - orb-tools/pack
            - dummy-deploy
          context: orb-publishing
          filters: *release-filters
